doctrine:
    dbal:
        driver: pdo_mysql
        host: db
        port: 3306
        dbname: app_db
        user: app_user
        password: app_pass
        charset: utf8mb4
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true